"""
Multi-page markdown analysis reports with embedded SVG figures.

Canonical deliverable format for this project: SVG is the only standard
visualization format; HTML (jnwb.report) is a web-facing rendering only,
not the source of truth. This module renders a session's canonical
stability + S+/S-/O+/X candidate audit (see
examples/07_canonical_stability_and_response_audit_v182o.py) into a
multi-page markdown bundle:

    outputs/markdown_reports/<session>/
        index.md              -- table of contents, headline numbers
        01_overview.md         -- session metadata, unit counts
        02_stability.md        -- canonical vs. live-proxy stability breakdown
        03_response_classification.md  -- S+/S-/O+/X candidate counts + table
        04_raster_suites.md     -- embedded SVG raster suites for units of interest
        figures/*.svg           -- copied/generated SVG figures referenced by the pages

Every number in these pages traces to a real CSV row or a real generated SVG;
nothing here is templated placeholder text.
"""

import logging
import shutil
from pathlib import Path
from typing import Optional
import pandas as pd

log = logging.getLogger(__name__)

OUTPUT_ROOT = Path("outputs/markdown_reports")


def _fmt_pct(n: int, d: int) -> str:
    return f"{n}/{d} ({100.0 * n / d:.1f}%)" if d > 0 else f"{n}/0 (n/a)"


def _write(path: Path, content: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    log.info(f"Wrote {path}")


def _page_overview(session_name: str, audit_df: pd.DataFrame) -> str:
    n_total = len(audit_df)
    n_areas = audit_df["area"].value_counts()
    lines = [
        f"# Session Overview — {session_name}",
        "",
        "[← Back to index](index.md) | [Next: Stability →](02_stability.md)",
        "",
        f"- **Total units**: {n_total}",
        f"- **Areas**: {', '.join(f'{a} (n={c})' for a, c in n_areas.items())}",
        "",
        "## Source data",
        "",
        f"- Canonical audit CSV: `outputs/publication_figures/canonical_audit_{session_name.replace('sub-', '').replace('_ses-', '_ses')}.csv`",
        "- Generated by: `examples/07_canonical_stability_and_response_audit_v182o.py`",
        "- Methodology reference: `outputs/archive/scripts/tag_stable_units.py` (stability), "
        "`outputs/archive/scripts/run_spk_response_metrics_a8_1.py` + `_response_metric_common.py` "
        "(S+/S-/O+/X candidate classification)",
        "",
    ]
    return "\n".join(lines)


def _page_stability(session_name: str, audit_df: pd.DataFrame) -> str:
    n_total = len(audit_df)
    n_canon = int(audit_df["is_stable_canonical"].sum())
    n_live = int(audit_df["is_stable"].sum()) if "is_stable" in audit_df.columns else None

    lines = [
        f"# Stability Audit — {session_name}",
        "",
        "[← Overview](01_overview.md) | [Next: Response Classification →](03_response_classification.md)",
        "",
        "## Canonical 3-criterion stability test",
        "",
        "A unit is canonically stable iff **all three** hold "
        "(`outputs/archive/scripts/tag_stable_units.py`):",
        "",
        "1. ≥5 spikes in *every* correct trial, window [-1000,+4000] ms around p1",
        "2. mean firing_rate ≥ 1.0 Hz",
        "3. presence_ratio ≥ 0.98 OR snr > 0.75",
        "",
        f"**Result: {_fmt_pct(n_canon, n_total)} units canonically stable.**",
        "",
    ]

    if n_live is not None:
        lines += [
            "## Comparison to the live jnwb.addressing proxy",
            "",
            f"- Live proxy (`quality >= 1.0`): {_fmt_pct(n_live, n_total)}",
            f"- Canonical 3-criterion test: {_fmt_pct(n_canon, n_total)}",
            "",
            "These are **not** the same test — see `jnwb/addressing.py` terminology note. "
            "The live proxy does not check trial-by-trial spike consistency or presence/SNR.",
            "",
        ]

    if "min_trial_spikes" in audit_df.columns:
        failing = audit_df[audit_df["is_stable_canonical"] == False].sort_values("min_trial_spikes")
        zero_spike = failing[failing["min_trial_spikes"] == 0]
        lines += [
            "## Units failing canonical stability with a zero-spike trial",
            "",
            f"{len(zero_spike)} units have at least one correct trial with **zero spikes** in the "
            "full [-1000,+4000] ms window — a quality red flag independent of any statistical test.",
            "",
        ]
        if len(zero_spike) > 0:
            cols = [c for c in ["area", "layer", "firing_rate", "min_trial_spikes"] if c in zero_spike.columns]
            lines.append(zero_spike[cols].head(20).to_markdown())
            lines.append("")

    return "\n".join(lines)


def _page_response_classification(session_name: str, audit_df: pd.DataFrame) -> str:
    n_total = len(audit_df)
    counts = audit_df["primary_candidate_label"].value_counts()

    lines = [
        f"# Response Classification — {session_name}",
        "",
        "[← Stability](02_stability.md) | [Next: Raster Suites →](04_raster_suites.md)",
        "",
        "## S+/S-/O+/X candidate pipeline",
        "",
        "Per-unit primary label, resolved by priority "
        "`X_candidate > O_plus_candidate > O_minus_candidate > S_plus_candidate > "
        "S_minus_candidate > null_or_unclassified`. Each label requires "
        "rate > 2.0 Hz, BH-FDR q < 0.05 (session-wide), and \\|Cohen's d\\| > 0.3 "
        "(`outputs/archive/scripts/run_spk_response_metrics_a8_1.py`).",
        "",
        "| Label | Count | % of session |",
        "|---|---|---|",
    ]
    for label, n in counts.items():
        lines.append(f"| `{label}` | {n} | {100.0*n/n_total:.1f}% |")
    lines.append("")

    n_om = int((counts.get("O_plus_candidate", 0) + counts.get("X_candidate", 0)))
    if n_om == 0:
        lines += [
            "**No O_plus_candidate or X_candidate units survive session-wide BH-FDR correction "
            "in this session.** This was verified against a raw (pre-correction) hit-rate sanity "
            "check to rule out a pipeline bug — raw hits exist at a plausible rate with near-zero "
            "median effect size, so the null result after correction is expected, not an error.",
            "",
        ]

    prime = audit_df[(audit_df["primary_candidate_label"] == "X_candidate") &
                      (audit_df["is_stable_canonical"] == True)]
    lines += [
        f"## 'Prime' units (X_candidate AND canonically stable): {len(prime)}",
        "",
    ]
    if len(prime) > 0:
        cols = [c for c in ["area", "layer", "primary_candidate_label"] if c in prime.columns]
        lines.append(prime[cols].to_markdown())
        lines.append("")

    return "\n".join(lines)


def _page_raster_suites(session_name: str, audit_df: pd.DataFrame,
                         highlight_units: Optional[list], figures_dir: Path,
                         source_svg_dir: Optional[Path]) -> str:
    lines = [
        f"# Raster Suites — {session_name}",
        "",
        "[← Response Classification](03_response_classification.md) | [Back to index](index.md)",
        "",
    ]

    if not highlight_units:
        lines += ["No units were selected for raster suite rendering in this pass.", ""]
        return "\n".join(lines)

    for uid in highlight_units:
        if uid not in audit_df.index:
            continue
        row = audit_df.loc[uid]
        label = row.get("primary_candidate_label", "unknown")
        area = row.get("area", "Unknown")
        stable = row.get("is_stable_canonical", None)

        svg_name = f"unit{uid}_raster_suite_12cond.svg"
        dest = figures_dir / svg_name
        if source_svg_dir is not None:
            src = source_svg_dir / svg_name
            if src.exists():
                dest.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy(src, dest)

        lines += [
            f"## Unit {uid} ({area})",
            "",
            f"- Canonical label: `{label}`",
            f"- Canonically stable: {stable}",
            "",
        ]
        if dest.exists():
            lines += [f"![Unit {uid} raster suite](figures/{svg_name})", ""]
        else:
            lines += [f"*(figure not found: expected at `{dest}`)*", ""]

    return "\n".join(lines)


def _page_index(session_name: str, audit_df: pd.DataFrame) -> str:
    n_total = len(audit_df)
    n_canon = int(audit_df["is_stable_canonical"].sum())
    n_om = int(audit_df["primary_candidate_label"].isin(["O_plus_candidate", "X_candidate"]).sum())

    lines = [
        f"# Analysis Report — {session_name}",
        "",
        f"*Generated by `jnwb.markdown_report`. All figures are SVG; this markdown bundle is the "
        f"canonical analysis artifact for this session — any HTML rendering is a web-facing mirror only.*",
        "",
        "## Pages",
        "",
        "1. [Overview](01_overview.md)",
        "2. [Stability Audit](02_stability.md)",
        "3. [Response Classification](03_response_classification.md)",
        "4. [Raster Suites](04_raster_suites.md)",
        "",
        "## Headline numbers",
        "",
        f"- Total units: {n_total}",
        f"- Canonically stable: {_fmt_pct(n_canon, n_total)}",
        f"- O+/X candidates (session-wide BH-FDR corrected): {n_om}",
        "",
    ]
    return "\n".join(lines)


def generate_markdown_report(session_name: str, audit_csv_path: str,
                              highlight_units: Optional[list] = None,
                              source_svg_dir: Optional[str] = None,
                              output_root: Path = OUTPUT_ROOT) -> Path:
    """
    Render a multi-page markdown report bundle for one session from its
    canonical audit CSV (as produced by examples/07_canonical_stability_and_response_audit_v182o.py).

    Args:
        session_name: e.g. "sub-V182o_ses-260629"
        audit_csv_path: path to the canonical_audit_<session>.csv file
        highlight_units: unit_ids to render raster suites for (must already have
            a pre-rendered `unit{id}_raster_suite_12cond.svg` in source_svg_dir)
        source_svg_dir: directory containing pre-rendered raster suite SVGs
        output_root: base directory for report bundles (default outputs/markdown_reports)

    Returns:
        Path to the bundle's index.md
    """
    audit_df = pd.read_csv(audit_csv_path)
    if "unit_id" in audit_df.columns:
        audit_df = audit_df.set_index("unit_id")

    session_dir = output_root / session_name
    figures_dir = session_dir / "figures"

    _write(session_dir / "index.md", _page_index(session_name, audit_df))
    _write(session_dir / "01_overview.md", _page_overview(session_name, audit_df))
    _write(session_dir / "02_stability.md", _page_stability(session_name, audit_df))
    _write(session_dir / "03_response_classification.md",
           _page_response_classification(session_name, audit_df))
    _write(session_dir / "04_raster_suites.md",
           _page_raster_suites(session_name, audit_df, highlight_units, figures_dir,
                                Path(source_svg_dir) if source_svg_dir else None))

    log.info(f"Markdown report bundle complete: {session_dir}")
    return session_dir / "index.md"


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    index_path = generate_markdown_report(
        session_name="sub-V182o_ses-260629",
        audit_csv_path="outputs/publication_figures/canonical_audit_V182o_ses260629.csv",
        highlight_units=[243, 150, 102, 261],
        source_svg_dir="outputs/jnwb_replications/o_plus_v182o",
    )
    print(f"Report bundle: {index_path.parent}")
