"""06-15: the jrsa correction fallback recorded a run as corrected a way it was not.

`_multiple_correction` routed every method but `bonferroni` to Benjamini-Hochberg when
`statsmodels` could not be imported, while `parameters['correction']` kept echoing the
method the caller asked for. A `holm`-corrected result was labelled `holm` and was in fact
`fdr_bh`, and nothing was raised or warned.

`statsmodels` is a declared hard dependency of jnwb, so the branch is reachable only where
a declared dependency is absent. These tests reach it by simulating the import failure --
never by changing the installed environment.

The discriminator is `test_holm_never_returns_the_benjamini_hochberg_values`. Restoring the
fallback makes it fail; the repair makes it pass. `test_holm_and_fdr_bh_genuinely_differ`
exists so the discriminator cannot pass for the wrong reason: if the seeded p-vector were
one on which the two methods happen to agree, the discriminator would be vacuous.

06-76 adds the second half. `'none'` was not a key of `_CORRECTION_METHOD_MAP`, so the same
substitution ran on the label `'none'` -- Benjamini-Hochberg with statsmodels present, and
an `ImportError` demanding statsmodels without it. The case set here was derived from that
map, so it could not reach a value the map was missing. `ACCEPTED_CORRECTIONS` is now a
literal and the map is checked against it.
"""

from __future__ import annotations

import contextlib
import sys

import numpy as np
import pytest

from jnwb.jrsa import _CORRECTION_METHOD_MAP, _multiple_correction
from jnwb.statistics import StatisticalAnalysis

ALPHA = 0.05

# Seeded, and pinned as a literal so the vector cannot drift with a NumPy RNG change.
# Produced by ``np.sort(np.random.default_rng(20615).uniform(0.001, 0.30, size=8))``.
P_SEEDED = np.array([
    0.06481467068559237,
    0.08142696682553835,
    0.10289033343814798,
    0.12915810801036298,
    0.15482611444191915,
    0.17419132734967072,
    0.25413064195097040,
    0.27595295241047440,
])

# Frozen with statsmodels present, before the repair. These are the values the repair must
# not move.
Q_STATSMODELS_PRESENT = {
    "fdr_bh": [
        0.2322551031328943, 0.2322551031328943, 0.2322551031328943,
        0.2322551031328943, 0.2322551031328943, 0.2322551031328943,
        0.2759529524104744, 0.2759529524104744,
    ],
    "fdr_by": [
        0.6312361910147591, 0.6312361910147591, 0.6312361910147591,
        0.6312361910147591, 0.6312361910147591, 0.6312361910147591,
        0.7500007028013250, 0.7500007028013250,
    ],
    "bonferroni": [
        0.5185173654847389, 0.6514157346043068, 0.8231226675051838,
        1.0, 1.0, 1.0, 1.0, 1.0,
    ],
    "holm": [
        0.5185173654847389, 0.5699887677787685, 0.6173420006288879,
        0.6457905400518149, 0.6457905400518149, 0.6457905400518149,
        0.6457905400518149, 0.6457905400518149,
    ],
    "holm-sidak": [
        0.41496549425878726, 0.4481820278730368, 0.4787174129915805,
        0.4991628178860116, 0.4991628178860116, 0.4991628178860116,
        0.4991628178860116, 0.4991628178860116,
    ],
}

# Every accepted value of `correction`, written out. This used to be spelled
# `set(_CORRECTION_METHOD_MAP) - {"bonferroni"}`, which derives the case set from the same
# structure that held the defect: a set generated by the map cannot reach a value the map is
# missing, and `'none'` was missing (P-50). The map is now checked against this literal
# rather than generating it.
#
# `jrsa`'s `correction` docstring also lists `cluster` and `maxT`. Neither is implemented --
# both raise `ValueError` -- so neither is an accepted value. That mismatch is a separate
# finding and is deliberately not decided here.
ACCEPTED_CORRECTIONS = (
    "bonferroni",
    "fdr_bh",
    "fdr_by",
    "holm",
    "holm-sidak",
    "none",
)

# The methods that cannot be computed at all without statsmodels. `bonferroni` is excluded
# because jnwb computes it itself; `none` because it computes nothing.
SUBSTITUTED_METHODS = sorted(set(ACCEPTED_CORRECTIONS) - {"bonferroni", "none"})


@contextlib.contextmanager
def statsmodels_unimportable():
    """Make ``import statsmodels...`` raise, without touching the environment.

    A cached submodule would satisfy ``from statsmodels.stats.multitest import ...`` from
    ``sys.modules`` and the branch under test would never run, so every cached
    ``statsmodels`` entry is masked, not just the top-level package.
    """
    saved = {
        name: mod for name, mod in sys.modules.items()
        if name == "statsmodels" or name.startswith("statsmodels.")
    }
    for name in saved:
        sys.modules[name] = None  # type: ignore[assignment]
    sys.modules["statsmodels"] = None  # type: ignore[assignment]
    try:
        yield
    finally:
        for name in [n for n in sys.modules
                     if n == "statsmodels" or n.startswith("statsmodels.")]:
            del sys.modules[name]
        sys.modules.update(saved)


def test_the_simulation_actually_blocks_the_import():
    """A simulation that silently fails to block would make every test below vacuous."""
    with statsmodels_unimportable():
        with pytest.raises(ImportError):
            from statsmodels.stats.multitest import multipletests  # noqa: F401
    from statsmodels.stats.multitest import multipletests  # noqa: F401  # restored


def test_holm_and_fdr_bh_genuinely_differ():
    """The discriminator's premise: on this vector the two methods disagree everywhere.

    Without this, a discriminator asserting they are unequal could pass on a repair that
    does nothing.
    """
    q_holm = _multiple_correction(P_SEEDED, "holm", ALPHA)
    q_bh = _multiple_correction(P_SEEDED, "fdr_bh", ALPHA)
    assert not np.any(q_holm == q_bh), (
        "seeded p-vector is unsuitable: holm and fdr_bh agree on at least one element, "
        "so the discriminator would pass without discriminating"
    )


def test_holm_never_returns_the_benjamini_hochberg_values():
    """THE DISCRIMINATOR for 06-15, asserting on both outcomes.

    With the fallback restored, `holm` returns exactly the Benjamini-Hochberg q-values
    under the label `holm`, and this fails. With the repair it raises instead.

    The refusal branch used to `return` before reaching any assertion, so on the repaired
    code the test enforced nothing while its name claimed enforcement (P-51). A refusal is
    an outcome to check: one that does not name the method it refused could be mistaken for
    another method's, which is the same mislabelling this test exists to forbid.
    """
    q_bh_fallback = np.asarray(StatisticalAnalysis.fdr_correct(P_SEEDED, method="bh"))

    with statsmodels_unimportable():
        try:
            q_holm = _multiple_correction(P_SEEDED, "holm", ALPHA)
        except ImportError as exc:
            assert "'holm'" in str(exc), (
                f"refusal does not name the method it refused: {exc}"
            )
            return

    assert not np.any(q_holm == q_bh_fallback), (
        "correction='holm' returned Benjamini-Hochberg values under the label 'holm': "
        f"holm={q_holm.tolist()} bh={q_bh_fallback.tolist()}"
    )


@pytest.mark.parametrize("method", SUBSTITUTED_METHODS)
def test_an_unavailable_estimator_raises_instead_of_substituting(method):
    with statsmodels_unimportable():
        with pytest.raises(ImportError, match="statsmodels"):
            _multiple_correction(P_SEEDED, method, ALPHA)


def test_the_map_offers_exactly_the_accepted_corrections():
    """The enumeration is the contract; the map must match it in both directions.

    Asserted against a literal. Against `_CORRECTION_METHOD_MAP` itself this would be a
    tautology -- it would agree with the map whatever the map said, including when an
    accepted value is missing from it, which is exactly how `'none'` went uncovered.
    """
    assert sorted(_CORRECTION_METHOD_MAP) == sorted(ACCEPTED_CORRECTIONS), (
        f"the map offers {sorted(_CORRECTION_METHOD_MAP)}, "
        f"the contract is {sorted(ACCEPTED_CORRECTIONS)}"
    )


@pytest.mark.parametrize("method", ACCEPTED_CORRECTIONS)
def test_every_accepted_correction_computes(method):
    """The case set the old derived spelling could not produce: it had no `'none'` case."""
    q = _multiple_correction(P_SEEDED, method, ALPHA)
    assert q.shape == P_SEEDED.shape
    assert q.dtype == np.float64
    assert np.all(np.isfinite(q))


def test_none_returns_the_p_values_uncorrected():
    """`'none'` means no correction. It used to mean Benjamini-Hochberg: `'none'` was not a
    key of the map, and `.get('none', 'fdr_bh')` returned BH q-values under the label."""
    q = _multiple_correction(P_SEEDED, "none", ALPHA)
    np.testing.assert_array_equal(q, P_SEEDED)
    assert q.dtype == np.float64
    assert q.shape == P_SEEDED.shape


def test_none_is_not_the_benjamini_hochberg_values():
    """Names the substitution directly. Element-wise inequality would be the wrong
    assertion here: Benjamini-Hochberg leaves the largest p-value unchanged."""
    q_none = _multiple_correction(P_SEEDED, "none", ALPHA)
    q_bh = _multiple_correction(P_SEEDED, "fdr_bh", ALPHA)
    assert not np.array_equal(q_none, q_bh), (
        f"correction='none' returned the Benjamini-Hochberg q-values: {q_none.tolist()}"
    )


def test_none_does_not_require_statsmodels():
    """Asking for no correction must not require the library that does correction. It used
    to raise `ImportError` here, demanding statsmodels in order to do nothing."""
    with statsmodels_unimportable():
        q = _multiple_correction(P_SEEDED, "none", ALPHA)
    np.testing.assert_array_equal(q, P_SEEDED)


def test_none_returns_a_copy_rather_than_the_callers_array():
    q = _multiple_correction(P_SEEDED, "none", ALPHA)
    q[0] = -1.0
    assert P_SEEDED[0] != -1.0, "correction='none' handed back the caller's own array"


def test_none_preserves_shape_on_a_two_dimensional_input():
    q = _multiple_correction(P_SEEDED.reshape(2, 4), "none", ALPHA)
    assert q.shape == (2, 4)
    np.testing.assert_array_equal(q.ravel(), P_SEEDED)


def test_bonferroni_still_computes_without_statsmodels():
    """Bonferroni is not a substitution: p*m clipped at 1 is Bonferroni, so the label
    stays true and the fallback is kept."""
    with statsmodels_unimportable():
        q = _multiple_correction(P_SEEDED, "bonferroni", ALPHA)
    np.testing.assert_array_equal(q, np.asarray(Q_STATSMODELS_PRESENT["bonferroni"]))


def test_the_bonferroni_multiplier_is_a_float_not_the_array_dtype():
    """`p_flat * len(p_flat)` kept the p-array's integer dtype, so the multiplier had to fit
    in it. Measured on NumPy 2.4.6: int8 with 200 tests raises `OverflowError: Python
    integer 200 out of bounds for int8`. The float multiplier is correct for every dtype and
    is bit-identical to the int multiplier on float input."""
    p_int = np.zeros(200, dtype=np.int8)
    p_int[0] = 1
    with statsmodels_unimportable():
        q = _multiple_correction(p_int, "bonferroni", ALPHA)
    expected = np.zeros(200, dtype=np.float64)
    expected[0] = 1.0
    np.testing.assert_array_equal(q, expected)
    assert q.dtype == np.float64


def test_the_raise_is_catchable_and_carries_its_cause():
    with statsmodels_unimportable():
        with pytest.raises(ImportError) as info:
            _multiple_correction(P_SEEDED, "holm", ALPHA)
    assert isinstance(info.value.__cause__, ImportError)


@pytest.mark.parametrize("method", sorted(Q_STATSMODELS_PRESENT))
def test_statsmodels_present_values_are_unchanged(method):
    """The repair touches only the branch where statsmodels is missing."""
    q = _multiple_correction(P_SEEDED, method, ALPHA)
    np.testing.assert_array_equal(q, np.asarray(Q_STATSMODELS_PRESENT[method]))
    assert q.dtype == np.float64
    assert q.shape == P_SEEDED.shape


def test_shape_and_dtype_survive_a_two_dimensional_input():
    q = _multiple_correction(P_SEEDED.reshape(2, 4), "holm", ALPHA)
    assert q.shape == (2, 4)
    assert q.dtype == np.float64
    np.testing.assert_array_equal(
        q.ravel(), np.asarray(Q_STATSMODELS_PRESENT["holm"])
    )
