"""Every documentation figure is what its generator draws today.

`docs/generate_figures.py` writes the ten PNGs under `docs/assets/figures/` from public jnwb
calls on seeded synthetic data. Nothing used to run it, so six committed figures drifted from
it -- one still showed a causal filter starting from zero, which the library stopped doing.

The comparison is on decoded pixels, not bytes: the PNG metadata changes between runs of the
same stack while no pixel does. Measured on one machine, two runs are byte-identical, and a
figure committed from an earlier plotting stack differs by one intensity level (1/255) in 0.01%
of its pixels. A changed figure differs far more: a regenerated title or label moves more
than 0.1 of the full scale in 0.6% to 1.9% of the pixels. So a pixel counts as changed when a
channel moves by more than 2/255, and a figure passes when fewer than 0.001% of its pixels
changed -- above the rendering noise, which measured zero, and below one changed digit, which the
self-test measures.

Rendering depends on the Matplotlib release. Figures written by 3.10.0 and regenerated by
3.10.8 differ by at most that one intensity level, so a patch release is compared. Across a minor
release no pixel tolerance holds: the ten figures written by 3.10.8 and redrawn by 3.11.2 differ
in 6 % to 11 % of their pixels, most by more than a quarter of the full scale, because the layout
moves. When the running minor release is not the one that wrote a figure (recorded in its PNG
metadata), the comparison is skipped with both versions named rather than failed on a difference
the stack made. An environment that must compare sets `JNWB_REQUIRE_FIGURE_COMPARISON=1`, and
there the skip is a failure: a run that compared nothing cannot pass as one that compared. One CI
leg pins the release the committed figures record and sets it; the last test here holds that leg
to the version the PNGs record.
"""
from __future__ import annotations

import ast
import os
import re
import subprocess
import sys
from pathlib import Path

import numpy as np
import pytest

matplotlib = pytest.importorskip("matplotlib")
import matplotlib.image as mpimg  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parents[1]
GENERATOR = REPO_ROOT / "docs" / "generate_figures.py"
FIGURE_DIR = REPO_ROOT / "docs" / "assets" / "figures"

CHANNEL_STEP = 2.0 / 255.0
# Rendering noise within one minor release measured exactly zero changed pixels on all ten
# figures, so the slack only has to absorb nothing; one changed digit of the smallest text in a
# documentation figure moves 1.3e-4.
CHANGED_FRACTION = 1e-5
#: Set to "1" where the comparison must run: a Matplotlib minor release other than the one that
#: wrote a figure then fails the test instead of skipping it. Any other value leaves it off, so
#: a CI leg can pass "0" explicitly.
REQUIRE_COMPARISON = "JNWB_REQUIRE_FIGURE_COMPARISON"
WORKFLOW = REPO_ROOT / ".github" / "workflows" / "workflow.yml"


def _registry():
    """The keys of the generator's FIGURES, read without running it: importing it would set
    this process's Matplotlib rcParams for every later test."""
    tree = ast.parse(GENERATOR.read_text(encoding="utf-8"))
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(getattr(t, "id", None) == "FIGURES" for t in node.targets):
            return {k.value for k in node.value.keys}
    raise AssertionError("docs/generate_figures.py defines no FIGURES registry")


def _software(png: Path) -> str:
    from PIL import Image

    with Image.open(png) as im:
        return str(im.info.get("Software", ""))


def _changed_fraction(a: np.ndarray, b: np.ndarray) -> float:
    if a.shape != b.shape:
        return 1.0
    moved = np.abs(a[..., :3].astype(float) - b[..., :3].astype(float)).max(axis=-1)
    return float(np.mean(moved > CHANNEL_STEP))


@pytest.fixture(scope="module")
def regenerated(tmp_path_factory):
    out = tmp_path_factory.mktemp("figures")
    subprocess.run(
        [sys.executable, str(GENERATOR), "--out-dir", str(out)],
        check=True, capture_output=True, text=True, cwd=REPO_ROOT, stdin=subprocess.DEVNULL,
    )
    return out


def test_every_committed_figure_has_a_generator():
    committed = {p.name for p in FIGURE_DIR.glob("*.png")}
    # Each registered figure is written once per theme: NAME.png (light) and NAME.dark.png.
    registered = {n for name in _registry() for n in (name, name.replace(".png", ".dark.png"))}
    assert committed == registered, (
        f"no generator: {sorted(committed - registered)}; "
        f"generator writes an uncommitted figure: {sorted(registered - committed)}"
    )


@pytest.mark.parametrize("name", sorted(p.name for p in FIGURE_DIR.glob("*.png")))
def test_the_committed_figure_is_what_the_generator_draws(name, regenerated):
    committed = FIGURE_DIR / name
    wrote = _software(committed)
    assert wrote.startswith("Matplotlib version"), (
        f"{name} records no Matplotlib version, so no environment could ever compare it; "
        "regenerate it with docs/generate_figures.py"
    )
    minor = ".".join(matplotlib.__version__.split(".")[:2])
    if not wrote.startswith(f"Matplotlib version{minor}."):
        why = f"{name} was written by {wrote!r}; running Matplotlib {matplotlib.__version__}"
        if os.environ.get(REQUIRE_COMPARISON) == "1":
            pytest.fail(f"{REQUIRE_COMPARISON} is set and no comparison is possible: {why}")
        pytest.skip(why)
    fraction = _changed_fraction(mpimg.imread(committed), mpimg.imread(regenerated / name))
    assert fraction < CHANGED_FRACTION, (
        f"{name}: {fraction:.4%} of pixels differ from `python docs/generate_figures.py "
        f"--only {name}`; regenerate it, or explain the drift"
    )


def test_the_tolerance_catches_a_one_digit_edit(tmp_path):
    """One changed digit of the smallest text, at the size and resolution of a documentation
    figure, is caught, and the same figure drawn twice is not. The digit moves 1.3e-4 of the
    pixels, so a slack loosened to 2e-4 fails here."""
    import matplotlib.pyplot as plt

    def draw(text, path):
        fig, ax = plt.subplots(figsize=(7.2, 3.2), dpi=180)
        ax.plot(np.linspace(0, 1, 50), np.linspace(0, 1, 50) ** 2)
        ax.text(0.5, 0.5, text, fontsize=7.5)
        fig.savefig(path)
        plt.close(fig)

    draw("AUC 0.876", tmp_path / "a.png")
    draw("AUC 0.876", tmp_path / "b.png")
    draw("AUC 0.875", tmp_path / "c.png")
    a, b, c = (mpimg.imread(tmp_path / n) for n in ("a.png", "b.png", "c.png"))
    assert _changed_fraction(a, b) == 0.0
    assert _changed_fraction(a, c) >= CHANGED_FRACTION, "one changed digit passed as unchanged"


def test_a_required_comparison_fails_instead_of_skipping(monkeypatch):
    committed = sorted(FIGURE_DIR.glob("*.png"))[0]
    monkeypatch.setenv(REQUIRE_COMPARISON, "1")
    monkeypatch.setattr(matplotlib, "__version__", "0.0.0")
    with pytest.raises(pytest.fail.Exception, match=REQUIRE_COMPARISON):
        test_the_committed_figure_is_what_the_generator_draws(committed.name, None)
    # "0" is how every other CI leg passes the variable, and it leaves the comparison off.
    for off in ("0", None):
        if off is None:
            monkeypatch.delenv(REQUIRE_COMPARISON)
        else:
            monkeypatch.setenv(REQUIRE_COMPARISON, off)
        with pytest.raises(pytest.skip.Exception):
            test_the_committed_figure_is_what_the_generator_draws(committed.name, None)


def test_one_ci_leg_compares_the_figures_at_the_version_that_wrote_them():
    """Every leg installed the newest Matplotlib, a minor release after the one that wrote the
    figures, so every leg skipped all of them and nothing compared a figure anywhere."""
    import yaml

    recorded = {_software(p) for p in FIGURE_DIR.glob("*.png")}
    versions = {m.group(1) for s in recorded if (m := re.match(r"Matplotlib version(\S+?),", s))}
    assert len(versions) == 1, f"the committed figures record several writers: {sorted(recorded)}"
    (written_by,) = versions

    job = yaml.safe_load(WORKFLOW.read_text(encoding="utf-8"))["jobs"]["test"]
    compared = [c for c in job["strategy"]["matrix"].get("include", [])
                if c.get("figures") == "compared"]
    assert len(compared) == 1, f"expected one leg with figures: compared, found {compared}"
    steps = job["steps"]
    pins = [s for s in steps if "matrix.figures == 'compared'" in str(s.get("if", ""))]
    assert len(pins) == 1, "the compared leg has no step of its own that pins Matplotlib"
    pinned = re.findall(r"matplotlib==(\S+?)[\"'\s]", pins[0]["run"] + " ")
    assert pinned == [written_by], (
        f"the compared leg pins {pinned}, the committed figures were written by {written_by}")
    names = [s.get("name") for s in steps]
    install = names.index("Install dependencies")
    suite = names.index("Run pytest")
    assert install < steps.index(pins[0]) < suite, "the pin must follow the install and precede the suite"
    env = str((steps[suite].get("env") or {}).get(REQUIRE_COMPARISON, ""))
    assert "matrix.figures == 'compared'" in env and "'1'" in env, (
        f"the suite step does not set {REQUIRE_COMPARISON}=1 on the compared leg: {env!r}")


def test_every_linux_leg_that_runs_the_suite_installs_arial_first():
    """The figures are drawn in Arial, which the ubuntu runners lack: a leg that ran the
    comparison without it would fail on the fallback font. Each such job installs the core
    fonts, with the licence accepted through debconf, before its first pytest step."""
    import yaml

    jobs = yaml.safe_load(WORKFLOW.read_text(encoding="utf-8"))["jobs"]
    checked = []
    for name, job in jobs.items():
        steps = job.get("steps", [])
        runs = [i for i, s in enumerate(steps) if "pytest" in str(s.get("run", ""))
                and "tests" in str(s.get("run", ""))]
        on = str(job.get("runs-on", ""))
        if not runs or ("windows" in on and "ubuntu" not in on):
            continue
        checked.append(name)
        fonts = [i for i, s in enumerate(steps)
                 if re.search(r"apt-get install\b[^\n]*ttf-mscorefonts-installer", str(s.get("run", "")))]
        assert fonts and fonts[0] < runs[0], f"job {name} runs the suite without installing Arial first"
        install = steps[fonts[0]]["run"]
        assert "debconf-set-selections" in install and "accepted-mscorefonts-eula select true" in install
    assert {"test", "test-floors", "build"} <= set(checked), checked
