# tests/test_generate_all_tfr_arrays.py
"""
Unit test for generate_all_tfr_arrays.py.
Verifies that the generated TFR array has the correct shape, dtype, and no NaNs/Infs.
"""

import numpy as np
from pathlib import Path

def test_generated_tfr_array_properties():
    file_path = Path("D:/workspace/data/tfr_arrays/sub-C31o_ses-230630-A-PFC-AXAB.npy")
    
    # Check that the file was successfully generated by the smoke test
    assert file_path.exists(), f"Expected smoke test file {file_path} to exist."
    
    # Load array (using mmap to be fast and memory-safe)
    arr = np.load(file_path, mmap_mode="r")
    
    # Verify dimensions and properties
    assert arr.ndim == 4, f"Expected 4D array, got {arr.ndim}D."
    assert arr.shape == (7, 128, 99, 500), f"Expected shape (7, 128, 99, 500), got {arr.shape}."
    assert arr.dtype == np.float32, f"Expected float32 dtype, got {arr.dtype}."
    
    # Load a small slice to check for finite values
    sample_slice = arr[0, 0, :10, :10]
    assert np.all(np.isfinite(sample_slice)), "Expected all values in the slice to be finite."
