"""Move every version surface to a new release.

    python scripts/bump_version.py X.Y.Z --date YYYY-MM-DD [--dry-run]

The surfaces are listed in `scripts/version_surfaces.py`, the module the tests read. Each file
is read and written as bytes, so its line endings are kept, and each anchor is counted before
and after the edit. The import profile is regenerated by `scripts/benchmark_import.py --write`
(it holds measured numbers, so it is not text-edited).

It does not assemble the changelog (`scripts/assemble_changelog.py`) or measure peak memory
(`scripts/measure_peak_memory.py --write`); CONTRIBUTING's "Releasing" runs those after this
and commits the bump first, so the memory is measured on a clean tree.
"""
from __future__ import annotations

import argparse
import datetime
import re
import subprocess
import sys
from pathlib import Path

_ROOT = str(Path(__file__).resolve().parent.parent)
if _ROOT not in sys.path:
    sys.path.append(_ROOT)
from scripts import version_surfaces as vs  # noqa: E402

VERSION = re.compile(r"\d+(?:\.\d+){2,3}")


def _tuple(version: str) -> tuple[int, ...]:
    return tuple(int(p) for p in version.split("."))


def _sub_once(data: bytes, pattern: "re.Pattern[bytes]", new: bytes, label: str) -> bytes:
    """Replace the value group of the one match of `pattern`; assert the count both sides."""
    found = pattern.findall(data)
    if len(found) != 1:
        raise SystemExit(f"{label}: expected 1 anchor before the edit, found {len(found)}")
    out = pattern.sub(lambda m: m.group(1) + new + m.group(4), data)
    if len(pattern.findall(out)) != 1 or pattern.search(out).group(3) != new:
        raise SystemExit(f"{label}: the edit did not leave exactly the new value")
    return out


def plan(root: Path, version: str, date: str) -> dict[Path, bytes]:
    """The new bytes of every text surface, computed and asserted before any is written."""
    old, _ = vs.read_init(root)
    edits: dict[Path, bytes] = {}
    path = root / vs.INIT
    data = _sub_once(path.read_bytes(), vs.VERSION_RE, version.encode(), "__version__")
    edits[path] = _sub_once(data, vs.DATE_RE, date.encode(), "__release_date__")
    for rel, template in vs.PINNED_CLAIMS:
        path = root / rel
        data = path.read_bytes()
        was, now = (template.format(version=v).encode() for v in (old, version))
        if data.count(was) != 1:
            raise SystemExit(f"{rel}: expected 1 of {was!r}, found {data.count(was)}")
        out = data.replace(was, now)
        if out.count(now) != 1 or (old != version and out.count(was) != 0):
            raise SystemExit(f"{rel}: the edit did not leave exactly the new claim")
        edits[path] = out
    return edits


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("version")
    ap.add_argument("--date", required=True, help="YYYY-MM-DD")
    ap.add_argument("--dry-run", action="store_true", help="print the changes, write nothing")
    ap.add_argument("--root", type=Path, default=vs.REPO_ROOT, help=argparse.SUPPRESS)
    ap.add_argument("--import-runs", type=int, default=10, help=argparse.SUPPRESS)
    args = ap.parse_args(argv)
    root = args.root.resolve()

    if not VERSION.fullmatch(args.version):
        raise SystemExit(f"{args.version!r} is not a release version (X.Y.Z or X.Y.Z.W)")
    try:
        datetime.date.fromisoformat(args.date)
    except ValueError:
        raise SystemExit(f"{args.date!r} is not a YYYY-MM-DD date")
    if not re.fullmatch(r"\d{4}-\d{2}-\d{2}", args.date):
        raise SystemExit(f"{args.date!r} is not a YYYY-MM-DD date")
    current, _ = vs.read_init(root)
    if _tuple(args.version) < _tuple(current):
        raise SystemExit(f"{args.version} is lower than the current version {current}")

    edits = plan(root, args.version, args.date)
    for path, new in edits.items():
        status = "changes" if path.read_bytes() != new else "unchanged"
        print(f"{status}: {path.relative_to(root).as_posix()}")
    print(f"regenerates: {vs.PROFILE}, {vs.BREAKDOWN} (scripts/benchmark_import.py --write)")
    if args.dry_run:
        print(f"dry run: {current} -> {args.version}, {args.date}; nothing written")
        return 0

    for path, new in edits.items():
        path.write_bytes(new)
    subprocess.run(
        [sys.executable, str(root / "scripts" / "benchmark_import.py"), "--write",
         "--runs", str(args.import_runs)],
        cwd=root, check=True, stdout=subprocess.DEVNULL)
    left = vs.problems(root)
    if left:
        raise SystemExit("surfaces still stale after the bump:\n  " + "\n  ".join(left))
    print(f"bumped {current} -> {args.version}, {args.date}; every surface agrees")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
