"""
Pilot rasters using shuffle-controlled S+/S-/O+ labels.

Prefer:
  outputs/classification/sub-C31o_ses-230816_rec_shuffle_class.csv
generated by:
  python scripts/classify_units_shuffle_sso.py --rasters

Falls back to building labels via classify_session_units if the CSV is missing.
"""

from __future__ import annotations

import csv
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd

import omission as oa
from omission.jnwb_ext.unit_classification import ClassificationConfig, classify_session_units
from omission.jnwb_ext.viz import raster_suite_omission

NWB_PATH = Path(r"D:/analysis/nwb/sub-C31o_ses-230816_rec.nwb")
CLASS_CSV = Path("outputs/classification/sub-C31o_ses-230816_rec_shuffle_class.csv")
OUT_ROOT = Path("outputs/rasters/sub-C31o_ses-230816_rec/shuffle_class")


def _pick_units(labels: pd.DataFrame) -> dict:
    picks = {}
    for cls in ("S+", "S-", "O+"):
        sub = labels[labels["display_class"] == cls]
        if sub.empty:
            continue
        if cls == "O+":
            pref = sub[sub["area"].astype(str).isin(["FEF", "PFC"])]
            picks[cls] = int((pref if len(pref) else sub).index[0])
        else:
            picks[cls] = int(sub.index[0])
    return picks


def main() -> None:
    if not NWB_PATH.is_file():
        raise FileNotFoundError(NWB_PATH)

    print(f"Loading {NWB_PATH}")
    session = oa.read(str(NWB_PATH), context="omission_glo_passive")

    if CLASS_CSV.is_file():
        labels = pd.read_csv(CLASS_CSV).set_index("unit_id")
        print(f"Loaded labels from {CLASS_CSV}")
    else:
        print("No classification CSV — running shuffle classifier…")
        labels = classify_session_units(
            session, cfg=ClassificationConfig(n_shuffles=1000)
        )
        CLASS_CSV.parent.mkdir(parents=True, exist_ok=True)
        labels.to_csv(CLASS_CSV)

    print(labels["display_class"].value_counts().to_string())
    picks = _pick_units(labels)
    if not picks:
        raise RuntimeError("No S+/S-/O+ units found to raster")

    OUT_ROOT.mkdir(parents=True, exist_ok=True)
    rows = []
    for cls, unit_id in picks.items():
        for col, val in (
            ("sig_s_plus", cls == "S+"),
            ("sig_s_minus", cls == "S-"),
            ("sig_o_plus", cls == "O+"),
        ):
            if col not in session._units_df.columns:
                session._units_df[col] = False
            session._units_df.loc[unit_id, col] = val

        out_dir = OUT_ROOT / cls.replace("+", "plus")
        out_dir.mkdir(parents=True, exist_ok=True)
        out_png = out_dir / f"unit_{unit_id}.png"
        print(f"Raster {cls} unit={unit_id} -> {out_png}")
        fig = raster_suite_omission(session, unit_id=unit_id)
        fig.savefig(out_png, dpi=200, bbox_inches="tight")
        plt.close(fig)
        rows.append({"display_class": cls, "unit_id": unit_id, "png": str(out_png)})

    man = OUT_ROOT / "pilot_manifest.csv"
    with man.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)
    print(f"Wrote {man}")


if __name__ == "__main__":
    main()
