r"""
Reclassify omission_grand_units.csv at a new ALPHA without rerunning the permutation stage.

scripts/classify_omission_units_grand.py's classification step (omission_class,
omission_class_v2, knows_when, knows_what, after_class) is a pure threshold comparison against
already-computed BH q-value columns (q1_q, q1_ramp_q, q2_q, q3_q, q4_q, q1v2_vs_pre_q,
q1v2_vs_all_q). bh() is a deterministic function of the raw p-values alone -- it does not read
ALPHA -- so those q-value columns are valid at any ALPHA and do not need recomputing. Only the
final `<= ALPHA` comparisons change. The full classify script's permutation stage (N_SHUF=1000
across 9,056 units, 4 question families) took 9,918s (~2h45m) per its own receipt
(outputs/classification/omission_grand_receipt.json) -- reclassifying from the existing table
avoids repeating that for what is a threshold change only.

ALPHA raised 0.025 -> 0.05, 2026-08-13, direct request (Hamm), corpus-wide -- see
artifacts/.lab/ for the discussion (fig03 panel-b/e/f O++ population count did not match
Hamm's expectation at the old threshold; q<=.05 with the existing peak+ramp conjunction test
was the confirmed replacement, checked against several other candidate thresholds first).

The classification block below is a byte-for-byte copy of
classify_omission_units_grand.py lines ~516-538 (omission_class through after_class), ALPHA
substituted. Any future change to that logic must be mirrored here or this script silently
drifts from the canonical one.
"""
import json
import os
import platform
import sys
from datetime import datetime, timezone

import numpy as np
import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from jnwb import paths as _P

OUT_DIR = _P.REPO_ROOT / "outputs/classification"
TABLE = OUT_DIR / "omission_grand_units.csv"
OLD_ALPHA = 0.025
NEW_ALPHA = 0.05


def main():
    df = pd.read_csv(TABLE)
    n = len(df)

    old_counts = {c: int((df.omission_class == c).sum()) for c in ["O++", "O+", "O-", "O--", "ns"]}

    ALPHA = NEW_ALPHA
    up = (df.q1_q <= ALPHA) & (df.q1_vs_pre_hz > 0) & (df.q1_vs_post_hz > 0)
    dn = (df.q1_q <= ALPHA) & (df.q1_vs_pre_hz < 0) & (df.q1_vs_post_hz < 0)
    rup = (df.q1_ramp_q <= ALPHA) & (df.q1_slope_effect > 0)
    rdn = (df.q1_ramp_q <= ALPHA) & (df.q1_slope_effect < 0)
    df["omission_class"] = np.where(up & rup, "O++", np.where(dn & rdn, "O--",
                            np.where(up, "O+", np.where(dn, "O-", "ns"))))

    v2_plus = (df.q1v2_vs_pre_q <= ALPHA) & (df.q1v2_vs_pre_hz > 0)
    v2_plusplus = v2_plus & (df.q1v2_vs_all_q <= ALPHA) & (df.q1v2_vs_all_hz > 0)
    df["omission_class_v2"] = np.where(v2_plusplus, "O++", np.where(v2_plus, "O+", "ns"))

    df["knows_when"] = df.q2_q <= ALPHA
    df["knows_what"] = df.q3_q <= ALPHA
    df["after_class"] = np.where((df.q4_q <= ALPHA) & (df.q4_dd_hz > 0), "Q+",
                         np.where((df.q4_q <= ALPHA) & (df.q4_dd_hz < 0), "Q-", "ns"))

    new_counts = {c: int((df.omission_class == c).sum()) for c in ["O++", "O+", "O-", "O--", "ns"]}
    new_counts_v2 = {c: int((df.omission_class_v2 == c).sum()) for c in ["O++", "O+", "ns"]}
    oplusplus_by_area = df[df.omission_class == "O++"].area10.value_counts().to_dict()

    df.to_csv(TABLE, index=False)

    # omission_grand_receipt.json is the canonical receipt classify_omission_units_grand.py
    # writes -- fig03_unit_census.py reads its alpha_fdr field directly to set panel a's own
    # significance threshold. Leaving it at the old alpha here would silently desync the
    # receipt from the table it describes (the classification columns above) -- update in
    # place rather than leaving a second, disagreeing source of truth.
    main_receipt_path = OUT_DIR / "omission_grand_receipt.json"
    main_receipt = json.load(open(main_receipt_path, encoding="utf-8"))
    main_receipt["alpha_fdr"] = NEW_ALPHA
    main_receipt["counts"] = new_counts
    main_receipt["counts_v2"] = new_counts_v2
    main_receipt["knows_when"] = int(df.knows_when.sum())
    main_receipt["knows_what"] = int(df.knows_what.sum())
    main_receipt["after_counts"] = {c: int((df.after_class == c).sum())
                                    for c in ["ns", "Q+", "Q-"]}
    main_receipt["reclassified"] = {
        "utc": datetime.now(timezone.utc).isoformat(),
        "script": os.path.abspath(__file__),
        "old_alpha": OLD_ALPHA, "new_alpha": NEW_ALPHA,
        "note": "permutation stage (n_shuffles/seed/runtime_s/env fields above) NOT rerun -- "
               "only the ALPHA threshold changed, applied to the existing q-value columns. "
               "counts/counts_v2/knows_when/knows_what/after_counts updated in place; "
               "v1_vs_v2_crosstab below is now stale (computed at the old alpha) and not "
               "regenerated by this script.",
    }
    with open(main_receipt_path, "w", encoding="utf-8") as fh:
        json.dump(main_receipt, fh, indent=2)

    receipt = {
        "generated_utc": datetime.now(timezone.utc).isoformat(),
        "script": os.path.abspath(__file__),
        "purpose": "reclassify omission_grand_units.csv at ALPHA=0.05 (was 0.025) without "
                  "rerunning the 9,918s permutation stage -- ALPHA only gates the final "
                  "threshold comparison, the q-value columns it compares against are "
                  "unaffected by it",
        "canonical_source": "scripts/classify_omission_units_grand.py -- this script copies "
                            "its classification block verbatim (lines ~516-538 as of "
                            "2026-08-13) and must be kept in sync if that logic changes",
        "old_alpha": OLD_ALPHA, "new_alpha": NEW_ALPHA,
        "n_units": n,
        "omission_class_OLD": old_counts, "omission_class_NEW": new_counts,
        "omission_class_v2_NEW": new_counts_v2,
        "oplusplus_by_area_NEW": oplusplus_by_area,
        "env": {"python": platform.python_version(), "numpy": np.__version__,
               "pandas": pd.__version__, "platform": platform.platform()},
    }
    with open(OUT_DIR / "reclassify_alpha05_receipt.json", "w", encoding="utf-8") as fh:
        json.dump(receipt, fh, indent=2)
    print(json.dumps(receipt, indent=2))


if __name__ == "__main__":
    main()
